#ifndef __PLATFORM_CONFIG_H__
#define __PLATFORM_CONFIG_H__

#define ROM_DATA_START_BANK 4
// TODO: Optimize.
#define USE_ACCURATE_RNG

#define SRAM_ADDRESS 0x8000
#define SRAM_BANK_SIZE 0x4000

#define VIEWPORT_WIDTH 20
#define VIEWPORT_HEIGHT 17
#define RENDER_ID_GG 0

#endif /* __PLATFORM_CONFIG_H__ */
