#ifndef __PLATFORM_CONFIG_H__
#define __PLATFORM_CONFIG_H__

#define ROM_DATA_START_BANK 4
#define USE_YERRICK_RNG

#define SRAM_ADDRESS 0xA000
#define SRAM_BANK_SIZE 0x2000

#define VIEWPORT_WIDTH 20
#define VIEWPORT_HEIGHT 18
#define RENDER_ID_DMG 0
#define RENDER_ID_GBC 1

#endif /* __PLATFORM_CONFIG_H__ */
