
# Platform specific flags for compiling (only populate if they're both present)
ifneq ($(strip $(PORT)),)
ifneq ($(strip $(PLAT)),)
LCCFLAGS += -m$(PORT):$(PLAT)
endif
endif

# Called by the individual targets below to build a ROM
build-target: $(BINS)

clean-target:
	rm -rf $(OBJDIR)
	rm -rf $(BINDIR)

gb-clean:
	${MAKE} clean-target TARGET=gb
gb:
	${MAKE} build-target PORT=sm83 PLAT=gb TARGET=gb


gb_tpp1-clean:
	${MAKE} clean-target TARGET=gb_tpp1
gb_tpp1:
	${MAKE} build-target PORT=sm83 PLAT=gb TARGET=gb_tpp1


pocket-clean:
	${MAKE} clean-target TARGET=pocket
pocket:
	${MAKE} build-target PORT=sm83 PLAT=ap TARGET=pocket


gg-clean:
	${MAKE} clean-target TARGET=gg
gg:
	${MAKE} build-target PORT=z80 PLAT=gg TARGET=gg
