#include "elements.h"
#include "elements_utils.h"
#include "gamevars.h"
#include "game.h"
#include "input.h"
#include "math.h"
#include "message_consts.h"
#include "oop.h"
#include "sound_consts.h"
#include "timer.h"

#include "elements_funcdefs.h"

#include "element_defs_character.inc"
#include "element_defs_color.inc"
#include "element_defs_flags.inc"
#include "element_defs_scorevalues.inc"
