#ifndef __MESSAGE_CONSTS_H__
#define __MESSAGE_CONSTS_H__

extern const char msg_gem_pickup_line1[];
extern const char msg_gem_pickup_line2[];
extern const char msg_torch_pickup_line1[];
extern const char msg_torch_pickup_line2[];
extern const char msg_torch_pickup_line3[];
extern const char msg_bomb_activated[];
extern const char msg_energizer_pickup_line1[];
extern const char msg_energizer_pickup_line2[];
extern const char msg_ammo_pickup[];
extern const char msg_invisible_touch_line1[];
extern const char msg_invisible_touch_line2[];
extern const char msg_forest_touch_line1[];
extern const char msg_forest_touch_line2[];
extern const char msg_fake_touch_line1[];
extern const char msg_fake_touch_line2[];
extern const char msg_water_touch_line1[];
extern const char msg_water_touch_line2[];
extern const char msg_no_shooting_line1[];
extern const char msg_no_shooting_line2[];
extern const char msg_out_of_line1[];
extern const char msg_out_of_ammo_line2[];
extern const char msg_out_of_torches_line2[];
extern const char msg_room_not_dark_line1[];
extern const char msg_room_not_dark_line2[];
extern const char msg_out_of_time[];
extern const char msg_ouch[];
extern const char msg_torch_hint_line1[];
extern const char msg_torch_hint_line2[];
extern const char msg_torch_hint_line3[];
extern const char msg_key_pickup_no[];
extern const char msg_key_pickup_yes[];
extern const char msg_key_pickup_08[];
extern const char msg_key_pickup_09[];
extern const char msg_key_pickup_0a[];
extern const char msg_key_pickup_0b[];
extern const char msg_key_pickup_0c[];
extern const char msg_key_pickup_0d[];
extern const char msg_key_pickup_0e[];
extern const char msg_key_pickup_0f[];
extern const char msg_door_open_no[];
extern const char msg_door_open_yes[];
extern const char msg_door_open_08[];
extern const char msg_door_open_09[];
extern const char msg_door_open_0a[];
extern const char msg_door_open_0b[];
extern const char msg_door_open_0c[];
extern const char msg_door_open_0d[];
extern const char msg_door_open_0e[];
extern const char msg_door_open_0f[];

#endif /* __MESSAGE_CONSTS_H__ */
